### PR TITLE
Added basic support for file api

### PR DESCRIPTION
**Pull request by mbgonicus**
Dirty, doesn't integrate well with the original file structure. Missing features:
- upload cancel
- upload progress
- firing events
- multiple uploads

Maybe we can start from here.

### CODE REVIEW

**Comment by mbgonicus** [comment]
@derrell Changed it to qx.bom.FileReader. I hope it's used correctly.

@johnspackman I wrote you on gitter.im; probably you haven't been online.

I'm using it like this to directly read json from a file, so it doesn't really create a file on the server when uploaded:

``` javascript
var button = new com.zenesis.qx.upload.UploadToolbarButton(this.tr("Upload JSON"));
// ...
var uploader = new com.zenesis.qx.upload.FileReader(button);
uploader.addListener("completeRead", function(event) {
  foo.MessageSerializer.json2messages(event.getData());
});
```

**Comment by johnspackman** [comment]
I was a bit confused at first how this fitted in with UploadMgr but Im starting to see what you mean now :)  Just so that I'm clear - this is to allow the user to upload a text file from their local disk to the browser?

My first thought is that the FileApiHandler is not a handler in the UploadMgr sense, ie it does not extend AbstractHandler and actually is kind of controller, parallel to UploadMgr itself - i.e. where UploadMgr manages a queue of uploads to the server, FileApiHandler manages a completely separate queue of file I/O to the web browser from the local disk.

There is some overlap, in that it uses the MParameters and InputElement classes but that doesn't seem very much, and it also seems a little limited in that it can only handle text files.

I'd also like to see some of the comments updated to expand on what its for and how it's used.

**Comment by mbgonicus** [comment]
> Just so that I'm clear - this is to allow the user to upload a text file from their local disk to the browser?

Yes, currently it can just do that. Actually I'm not really sure if you can use File API to save a file on a server.

> it also seems a little limited in that it can only handle text files

Adding the other [read methods](http://demo.qooxdoo.org/current/apiviewer/#qx.bom.FileReader) shouldn't be to complicated.

@derrell Do you know why [FileReader.readAsArrayBuffer()](https://developer.mozilla.org/de/docs/Web/API/FileReader) hasn't an equivalent in qx.bom.FileReader?

> I'd also like to see some of the comments updated to expand on what its for and how it's used.

I agree.

So, do you think this could be a starting point for really integrating the File API?

**Comment by derrell** [comment]
@mbgonicus I think at the time I wrote this, that function was not well supported by the browsers. Maybe it could be added now?

**Comment by johnspackman** [comment]
> Actually I'm not really sure if you can use File API to save a file on a server.

You can, this is how XhrHandler works :)  

> Adding the other read methods shouldn't be to complicated.

I agree

Im wondering if this can be simplified - as this is uploading from the local disk to the browser, there is async support in the API but is it really necessary to manage a queue?

**Comment by mbgonicus** [comment]
@derrell Yes, adding that should be really simple. I try to get a few minutes today for adding it.

@johnspackman 

> Im wondering if this can be simplified - as this is uploading from the local disk to the browser, there is async support in the API but is it really necessary to manage a queue? 

Unfortunately, I'm not really into this topic enough to evaluate that question. Guess I need to read about the File API to get the necessary background information...

**Comment by johnspackman** [comment]
Closing this as it seems there is some work to do first.  @mbgonicus please feel free to reopen or create a new PR when you're ready

**Pull request closed without merging**
