### PR TITLE
add npm support

### PR DESCRIPTION
**Pull request by valette**
Hi!

This file would allow direct installation using npm.

On a side note, I published UploadMgr as an npm module here : 
https://www.npmjs.com/package/uploadmgr

What is your opinion about it?

### CODE REVIEW

**Comment by johnspackman** [comment]
I like it :)  The only change is that the home page is the github repo (contrib v3 is being rolled out this week and the new policy is to move the contrib homepage off qooxdoo.org onto the contrib's repo), I've just fixed that - how can I update npm with my change?

**Comment by johnspackman** [comment]
Can you add me as a collaborator so that I can update the npm package?  I've just created a user account at npmjs called johnspackman

**Comment by valette** [comment]
> Can you add me as a collaborator so that I can update the npm package? I've just created a user account at npmjs called johnspackman

done!

**Comment by johnspackman** [comment]
cool :)  well thats something new I've learned today - i'll publish my other contribs there too later

**Pull request merged**
